### ISSUE TITLE
`DateTime` encoding defaults to microseconds?

### ISSUE THREAD

**Issue by andyferris** [JuliaData/Avro.jl#8]
Hi @quinnj,

Just starting using this great package - seems perfect for our use! Thanks.

I was curious why the default `schematype` for `DateTime`is in microseconds? It would seem more natural to export milliseconds by default given that is the precision used in Julia.

**Comment by quinnj** [comment]
Good question; I'm not sure I remember why it was `LocalTimestampMicrosType` instead of `LocalTimestampMillisType`. happy to accept a PR if you need it changed.
